additional_board_urls:
  - "https://raw.githubusercontent.com/washed/CO2-Ampel/master/package_co2ampel_index.json"
boards:
  - arduino:samd
  - co2ampel:samd
libraries:
  - ArduinoJson
compile:
  verbose: true
  warnings: more
  board_type: co2ampel:samd:sb
  project_dir: CO2-Ampel_Plus
